### ISSUE TITLE
Not working and weird knock bug

### ISSUE THREAD

**Issue by TazAileen** [LXE97/SeamlessArrowNocking#1]
I can't get it to work for some reason. I tried installing it into my SkyrimVR/Data/SKSE/Plugins, installing it via MO2 with my own zip path, changing from Simple Realistic Archery 0 to the new one and all of it's dependencies and turning iLeftHandedMode to 0 in the ini. All that's happened so far is that it either acts like vanilla or my character gets stuck not being able to draw or gets stuck in knock not being able to shoot. I'm playing on Quest 3 and I'm using the SpellWheelVR layout. Here's a video of my issues: https://www.youtube.com/watch?v=-5DU2Uhr0As

**Comment by TazAlonzo** [comment]
I'm using Quest 3 and layout is the SpellWheel VR one

**Comment by LXE97** [comment]
thanks for the feedback! Do you mind posting Documents\My Games\Skyrim VR\SKSE\ZSeamlessArrowNocking.log if you have it? I'll test with SpellWheelVR, I have a hunch.

**Comment by TazAileen** [comment]
Hmm weird, I don't have that file. Only ini, dll, and pdb

**Comment by TazAileen** [comment]
Just tried making a txt file and renaming it ZSeamlessArrrowKnocking.log and played until I got the glitches, but the file is still empty.
